### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by awsp** [awsp/linvodb-viewer#1]
## ToDo List
- [ ] Ability to add/remove/modify entity
- [ ] Multiple windows / tabs
- [ ] Gulp build script
- [ ] Queries support
- [ ] Filtering
- [ ] Watch db changes
- [x] Refresh databaes
- [x] App icon
